from .openai_imagenet_template import openai_imagenet_template
from .openai_imagenet_template_reduced import openai_imagenet_template_reduced
from .simple_template import simple_template
from .iwildcam_template import iwildcam_template